### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by omgovich** [omgovich/react-colorful#126]
Hey, @rschristian @molefrog!
Seems like we might have issues with Next.js, but I didn't get the reasons yet. 
Created an empty next.js project and added the color picker to it:

![image](https://user-images.githubusercontent.com/206567/115533282-440af280-a29f-11eb-81ed-d3c88b1205ef.png)

![image](https://user-images.githubusercontent.com/206567/115534749-c21bc900-a2a0-11eb-90c1-753e1f049ff3.png)

Do you have any ideas?

**Comment by omgovich** [comment]
Hmmm. For some reason `npm install react-colorful` adds all our "devDependencies" (including react^17.0.0) as "dependencies" to package-lock.json and I assume that adds a second react instance on the server.

![image](https://user-images.githubusercontent.com/206567/115537327-630b8380-a2a3-11eb-909c-a4b036fffc28.png)

**Comment by omgovich** [comment]
Hmm, I don't know what was that. But it was fixed once I removed node_modules and package-lock.json. Super weird. 

![image](https://user-images.githubusercontent.com/206567/115537977-0fe60080-a2a4-11eb-8825-0b43d1e1fc76.png)

**Comment by deadcoder0904** [comment]
This is happening to me for the last couple of days on various old projects where I try to update dependencies & then it just throws weird peer-dependencies error.

After I clean my cache & remove `package-lock.json` & `node_modules`, it starts to work. Seems like an npm issue.

**Comment by cschram** [comment]
I'm still seeing this error when using react-colorful with Next.js, even after deleting `node_modules` and `package-lock.json`, clearing npm cache, and reinstalling dependencies.

**Comment by omgovich** [comment]
Hi! Could you please share versions of Node.js and Next.js you have?

**Comment by cschram** [comment]
Node 16.9.1 and Next.js 11.0.1
